'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace MWGift45

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"), _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard", ConfigurationName:="MWGift45.GiftcardSoap")> _
    Public Interface GiftcardSoap

        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard/ActivateCard", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)> _
        Function ActivateCard(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.ActivateCardRequest) As MWGift45.GiftResponse45

        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard/ActivateCard", ReplyAction:="*")> _
        Function ActivateCardAsync(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.ActivateCardRequest) As System.Threading.Tasks.Task(Of MWGift45.GiftResponse45)

        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard/AddValue", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)> _
        Function AddValue(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.AddValueRequest) As MWGift45.GiftResponse45

        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard/AddValue", ReplyAction:="*")> _
        Function AddValueAsync(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.AddValueRequest) As System.Threading.Tasks.Task(Of MWGift45.GiftResponse45)

        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard/BalanceInquiry", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)> _
        Function BalanceInquiry(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.BalanceInquiryRequest) As MWGift45.GiftResponse45

        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard/BalanceInquiry", ReplyAction:="*")> _
        Function BalanceInquiryAsync(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.BalanceInquiryRequest) As System.Threading.Tasks.Task(Of MWGift45.GiftResponse45)

        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard/Refund", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)> _
        Function Refund(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.GiftRefundRequest) As MWGift45.GiftResponse45

        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard/Refund", ReplyAction:="*")> _
        Function RefundAsync(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.GiftRefundRequest) As System.Threading.Tasks.Task(Of MWGift45.GiftResponse45)

        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard/Sale", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)> _
        Function Sale(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.GiftSaleRequest) As MWGift45.GiftResponse45

        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard/Sale", ReplyAction:="*")> _
        Function SaleAsync(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.GiftSaleRequest) As System.Threading.Tasks.Task(Of MWGift45.GiftResponse45)

        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard/Void", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)> _
        Function Void(ByVal Credentials As MWGift45.MerchantCredentials, ByVal Request As MWGift45.GiftVoidRequest) As MWGift45.GiftResponse45

        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard/Void", ReplyAction:="*")> _
        Function VoidAsync(ByVal Credentials As MWGift45.MerchantCredentials, ByVal Request As MWGift45.GiftVoidRequest) As System.Threading.Tasks.Task(Of MWGift45.GiftResponse45)

        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard/AddPoints", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)> _
        Function AddPoints(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.AddPointsRequest) As MWGift45.GiftResponse45

        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard/AddPoints", ReplyAction:="*")> _
        Function AddPointsAsync(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.AddPointsRequest) As System.Threading.Tasks.Task(Of MWGift45.GiftResponse45)

        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard/RemovePoints", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)> _
        Function RemovePoints(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.RemovePointsRequest) As MWGift45.GiftResponse45

        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard/RemovePoints", ReplyAction:="*")> _
        Function RemovePointsAsync(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.RemovePointsRequest) As System.Threading.Tasks.Task(Of MWGift45.GiftResponse45)
    End Interface

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard")> _
    Partial Public Class MerchantCredentials
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private merchantNameField As String

        Private merchantSiteIdField As String

        Private merchantKeyField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)> _
        Public Property MerchantName() As String
            Get
                Return Me.merchantNameField
            End Get
            Set
                Me.merchantNameField = value
                Me.RaisePropertyChanged("MerchantName")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)> _
        Public Property MerchantSiteId() As String
            Get
                Return Me.merchantSiteIdField
            End Get
            Set
                Me.merchantSiteIdField = value
                Me.RaisePropertyChanged("MerchantSiteId")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)> _
        Public Property MerchantKey() As String
            Get
                Return Me.merchantKeyField
            End Get
            Set
                Me.merchantKeyField = value
                Me.RaisePropertyChanged("MerchantKey")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard")> _
    Partial Public Class RemovePointsRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private amountTypeField As String

        Private amountField As String

        Private invoiceNumberField As String

        Private merchantTransactionIdField As String

        Private customerEmailAddressField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)> _
        Public Property AmountType() As String
            Get
                Return Me.amountTypeField
            End Get
            Set
                Me.amountTypeField = value
                Me.RaisePropertyChanged("AmountType")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)> _
        Public Property Amount() As String
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
                Me.RaisePropertyChanged("Amount")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)> _
        Public Property InvoiceNumber() As String
            Get
                Return Me.invoiceNumberField
            End Get
            Set
                Me.invoiceNumberField = value
                Me.RaisePropertyChanged("InvoiceNumber")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)> _
        Public Property MerchantTransactionId() As String
            Get
                Return Me.merchantTransactionIdField
            End Get
            Set
                Me.merchantTransactionIdField = value
                Me.RaisePropertyChanged("MerchantTransactionId")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)> _
        Public Property CustomerEmailAddress() As String
            Get
                Return Me.customerEmailAddressField
            End Get
            Set
                Me.customerEmailAddressField = value
                Me.RaisePropertyChanged("CustomerEmailAddress")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard")> _
    Partial Public Class AddPointsRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private amountTypeField As String

        Private amountField As String

        Private invoiceNumberField As String

        Private merchantTransactionIdField As String

        Private customerEmailAddressField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)> _
        Public Property AmountType() As String
            Get
                Return Me.amountTypeField
            End Get
            Set
                Me.amountTypeField = value
                Me.RaisePropertyChanged("AmountType")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)> _
        Public Property Amount() As String
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
                Me.RaisePropertyChanged("Amount")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)> _
        Public Property InvoiceNumber() As String
            Get
                Return Me.invoiceNumberField
            End Get
            Set
                Me.invoiceNumberField = value
                Me.RaisePropertyChanged("InvoiceNumber")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)> _
        Public Property MerchantTransactionId() As String
            Get
                Return Me.merchantTransactionIdField
            End Get
            Set
                Me.merchantTransactionIdField = value
                Me.RaisePropertyChanged("MerchantTransactionId")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)> _
        Public Property CustomerEmailAddress() As String
            Get
                Return Me.customerEmailAddressField
            End Get
            Set
                Me.customerEmailAddressField = value
                Me.RaisePropertyChanged("CustomerEmailAddress")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard")> _
    Partial Public Class GiftVoidRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private tokenField As String

        Private invoiceNumberField As String

        Private merchantTransactionIdField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)> _
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
                Me.RaisePropertyChanged("Token")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)> _
        Public Property InvoiceNumber() As String
            Get
                Return Me.invoiceNumberField
            End Get
            Set
                Me.invoiceNumberField = value
                Me.RaisePropertyChanged("InvoiceNumber")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)> _
        Public Property MerchantTransactionId() As String
            Get
                Return Me.merchantTransactionIdField
            End Get
            Set
                Me.merchantTransactionIdField = value
                Me.RaisePropertyChanged("MerchantTransactionId")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard")> _
    Partial Public Class GiftSaleRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private amountField As String

        Private invoiceNumberField As String

        Private enablePartialAuthorizationField As String

        Private merchantTransactionIdField As String

        Private customerEmailAddressField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)> _
        Public Property Amount() As String
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
                Me.RaisePropertyChanged("Amount")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)> _
        Public Property InvoiceNumber() As String
            Get
                Return Me.invoiceNumberField
            End Get
            Set
                Me.invoiceNumberField = value
                Me.RaisePropertyChanged("InvoiceNumber")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)> _
        Public Property EnablePartialAuthorization() As String
            Get
                Return Me.enablePartialAuthorizationField
            End Get
            Set
                Me.enablePartialAuthorizationField = value
                Me.RaisePropertyChanged("EnablePartialAuthorization")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)> _
        Public Property MerchantTransactionId() As String
            Get
                Return Me.merchantTransactionIdField
            End Get
            Set
                Me.merchantTransactionIdField = value
                Me.RaisePropertyChanged("MerchantTransactionId")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)> _
        Public Property CustomerEmailAddress() As String
            Get
                Return Me.customerEmailAddressField
            End Get
            Set
                Me.customerEmailAddressField = value
                Me.RaisePropertyChanged("CustomerEmailAddress")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard")> _
    Partial Public Class GiftRefundRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private amountField As String

        Private invoiceNumberField As String

        Private merchantTransactionIdField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)> _
        Public Property Amount() As String
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
                Me.RaisePropertyChanged("Amount")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)> _
        Public Property InvoiceNumber() As String
            Get
                Return Me.invoiceNumberField
            End Get
            Set
                Me.invoiceNumberField = value
                Me.RaisePropertyChanged("InvoiceNumber")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)> _
        Public Property MerchantTransactionId() As String
            Get
                Return Me.merchantTransactionIdField
            End Get
            Set
                Me.merchantTransactionIdField = value
                Me.RaisePropertyChanged("MerchantTransactionId")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard")> _
    Partial Public Class BalanceInquiryRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private invoiceNumberField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)> _
        Public Property InvoiceNumber() As String
            Get
                Return Me.invoiceNumberField
            End Get
            Set
                Me.invoiceNumberField = value
                Me.RaisePropertyChanged("InvoiceNumber")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard")> _
    Partial Public Class AddValueRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private amountField As String

        Private invoiceNumberField As String

        Private merchantTransactionIdField As String

        Private customerEmailAddressField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)> _
        Public Property Amount() As String
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
                Me.RaisePropertyChanged("Amount")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)> _
        Public Property InvoiceNumber() As String
            Get
                Return Me.invoiceNumberField
            End Get
            Set
                Me.invoiceNumberField = value
                Me.RaisePropertyChanged("InvoiceNumber")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)> _
        Public Property MerchantTransactionId() As String
            Get
                Return Me.merchantTransactionIdField
            End Get
            Set
                Me.merchantTransactionIdField = value
                Me.RaisePropertyChanged("MerchantTransactionId")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)> _
        Public Property CustomerEmailAddress() As String
            Get
                Return Me.customerEmailAddressField
            End Get
            Set
                Me.customerEmailAddressField = value
                Me.RaisePropertyChanged("CustomerEmailAddress")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard")> _
    Partial Public Class LoyaltyDetail
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private pointsTypeField As String

        Private approvedPointsField As String

        Private pointsBeforeNextRewardField As String

        Private pointsBalanceField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)> _
        Public Property PointsType() As String
            Get
                Return Me.pointsTypeField
            End Get
            Set
                Me.pointsTypeField = value
                Me.RaisePropertyChanged("PointsType")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)> _
        Public Property ApprovedPoints() As String
            Get
                Return Me.approvedPointsField
            End Get
            Set
                Me.approvedPointsField = value
                Me.RaisePropertyChanged("ApprovedPoints")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)> _
        Public Property PointsBeforeNextReward() As String
            Get
                Return Me.pointsBeforeNextRewardField
            End Get
            Set
                Me.pointsBeforeNextRewardField = value
                Me.RaisePropertyChanged("PointsBeforeNextReward")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)> _
        Public Property PointsBalance() As String
            Get
                Return Me.pointsBalanceField
            End Get
            Set
                Me.pointsBalanceField = value
                Me.RaisePropertyChanged("PointsBalance")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard")> _
    Partial Public Class GiftDetail
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private approvedAmountField As String

        Private requestedAmountField As String

        Private giftBalanceField As String

        Private rewardsBalanceField As String

        Private redeemableBalanceField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)> _
        Public Property ApprovedAmount() As String
            Get
                Return Me.approvedAmountField
            End Get
            Set
                Me.approvedAmountField = value
                Me.RaisePropertyChanged("ApprovedAmount")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)> _
        Public Property RequestedAmount() As String
            Get
                Return Me.requestedAmountField
            End Get
            Set
                Me.requestedAmountField = value
                Me.RaisePropertyChanged("RequestedAmount")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)> _
        Public Property GiftBalance() As String
            Get
                Return Me.giftBalanceField
            End Get
            Set
                Me.giftBalanceField = value
                Me.RaisePropertyChanged("GiftBalance")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)> _
        Public Property RewardsBalance() As String
            Get
                Return Me.rewardsBalanceField
            End Get
            Set
                Me.rewardsBalanceField = value
                Me.RaisePropertyChanged("RewardsBalance")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)> _
        Public Property RedeemableBalance() As String
            Get
                Return Me.redeemableBalanceField
            End Get
            Set
                Me.redeemableBalanceField = value
                Me.RaisePropertyChanged("RedeemableBalance")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard")> _
    Partial Public Class GiftResponse45
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private approvalStatusField As String

        Private cardNumberField As String

        Private errorMessageField As String

        Private expirationDateField As String

        Private invoiceNumberField As String

        Private readerEntryModeField As String

        Private responseMessageField As String

        Private tokenField As String

        Private transactionDateField As String

        Private giftField As GiftDetail

        Private loyaltyField As LoyaltyDetail

        Private customerEmailAddressField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)> _
        Public Property ApprovalStatus() As String
            Get
                Return Me.approvalStatusField
            End Get
            Set
                Me.approvalStatusField = value
                Me.RaisePropertyChanged("ApprovalStatus")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)> _
        Public Property CardNumber() As String
            Get
                Return Me.cardNumberField
            End Get
            Set
                Me.cardNumberField = value
                Me.RaisePropertyChanged("CardNumber")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)> _
        Public Property ErrorMessage() As String
            Get
                Return Me.errorMessageField
            End Get
            Set
                Me.errorMessageField = value
                Me.RaisePropertyChanged("ErrorMessage")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)> _
        Public Property ExpirationDate() As String
            Get
                Return Me.expirationDateField
            End Get
            Set
                Me.expirationDateField = value
                Me.RaisePropertyChanged("ExpirationDate")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)> _
        Public Property InvoiceNumber() As String
            Get
                Return Me.invoiceNumberField
            End Get
            Set
                Me.invoiceNumberField = value
                Me.RaisePropertyChanged("InvoiceNumber")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)> _
        Public Property ReaderEntryMode() As String
            Get
                Return Me.readerEntryModeField
            End Get
            Set
                Me.readerEntryModeField = value
                Me.RaisePropertyChanged("ReaderEntryMode")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)> _
        Public Property ResponseMessage() As String
            Get
                Return Me.responseMessageField
            End Get
            Set
                Me.responseMessageField = value
                Me.RaisePropertyChanged("ResponseMessage")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)> _
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
                Me.RaisePropertyChanged("Token")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)> _
        Public Property TransactionDate() As String
            Get
                Return Me.transactionDateField
            End Get
            Set
                Me.transactionDateField = value
                Me.RaisePropertyChanged("TransactionDate")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)> _
        Public Property Gift() As GiftDetail
            Get
                Return Me.giftField
            End Get
            Set
                Me.giftField = value
                Me.RaisePropertyChanged("Gift")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)> _
        Public Property Loyalty() As LoyaltyDetail
            Get
                Return Me.loyaltyField
            End Get
            Set
                Me.loyaltyField = value
                Me.RaisePropertyChanged("Loyalty")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)> _
        Public Property CustomerEmailAddress() As String
            Get
                Return Me.customerEmailAddressField
            End Get
            Set
                Me.customerEmailAddressField = value
                Me.RaisePropertyChanged("CustomerEmailAddress")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard")> _
    Partial Public Class ActivateCardRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private amountField As String

        Private invoiceNumberField As String

        Private merchantTransactionIdField As String

        Private customerEmailAddressField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)> _
        Public Property Amount() As String
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
                Me.RaisePropertyChanged("Amount")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)> _
        Public Property InvoiceNumber() As String
            Get
                Return Me.invoiceNumberField
            End Get
            Set
                Me.invoiceNumberField = value
                Me.RaisePropertyChanged("InvoiceNumber")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)> _
        Public Property MerchantTransactionId() As String
            Get
                Return Me.merchantTransactionIdField
            End Get
            Set
                Me.merchantTransactionIdField = value
                Me.RaisePropertyChanged("MerchantTransactionId")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)> _
        Public Property CustomerEmailAddress() As String
            Get
                Return Me.customerEmailAddressField
            End Get
            Set
                Me.customerEmailAddressField = value
                Me.RaisePropertyChanged("CustomerEmailAddress")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.merchantwarehouse.com/merchantware/45/Giftcard")> _
    Partial Public Class GiftPaymentData
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged

        Private sourceField As String

        Private giftCardPinField As String

        Private trackDataField As String

        Private cardNumberField As String

        Private tokenField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)> _
        Public Property Source() As String
            Get
                Return Me.sourceField
            End Get
            Set
                Me.sourceField = value
                Me.RaisePropertyChanged("Source")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)> _
        Public Property GiftCardPin() As String
            Get
                Return Me.giftCardPinField
            End Get
            Set
                Me.giftCardPinField = value
                Me.RaisePropertyChanged("GiftCardPin")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)> _
        Public Property TrackData() As String
            Get
                Return Me.trackDataField
            End Get
            Set
                Me.trackDataField = value
                Me.RaisePropertyChanged("TrackData")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)> _
        Public Property CardNumber() As String
            Get
                Return Me.cardNumberField
            End Get
            Set
                Me.cardNumberField = value
                Me.RaisePropertyChanged("CardNumber")
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)> _
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
                Me.RaisePropertyChanged("Token")
            End Set
        End Property

        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")> _
    Public Interface GiftcardSoapChannel
        Inherits MWGift45.GiftcardSoap, System.ServiceModel.IClientChannel
    End Interface

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")> _
    Partial Public Class GiftcardSoapClient
        Inherits System.ServiceModel.ClientBase(Of MWGift45.GiftcardSoap)
        Implements MWGift45.GiftcardSoap

        Public Sub New()
            MyBase.New
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub

        Public Function ActivateCard(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.ActivateCardRequest) As MWGift45.GiftResponse45 Implements MWGift45.GiftcardSoap.ActivateCard
            Return MyBase.Channel.ActivateCard(Credentials, PaymentData, Request)
        End Function

        Public Function ActivateCardAsync(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.ActivateCardRequest) As System.Threading.Tasks.Task(Of MWGift45.GiftResponse45) Implements MWGift45.GiftcardSoap.ActivateCardAsync
            Return MyBase.Channel.ActivateCardAsync(Credentials, PaymentData, Request)
        End Function

        Public Function AddValue(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.AddValueRequest) As MWGift45.GiftResponse45 Implements MWGift45.GiftcardSoap.AddValue
            Return MyBase.Channel.AddValue(Credentials, PaymentData, Request)
        End Function

        Public Function AddValueAsync(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.AddValueRequest) As System.Threading.Tasks.Task(Of MWGift45.GiftResponse45) Implements MWGift45.GiftcardSoap.AddValueAsync
            Return MyBase.Channel.AddValueAsync(Credentials, PaymentData, Request)
        End Function

        Public Function BalanceInquiry(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.BalanceInquiryRequest) As MWGift45.GiftResponse45 Implements MWGift45.GiftcardSoap.BalanceInquiry
            Return MyBase.Channel.BalanceInquiry(Credentials, PaymentData, Request)
        End Function

        Public Function BalanceInquiryAsync(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.BalanceInquiryRequest) As System.Threading.Tasks.Task(Of MWGift45.GiftResponse45) Implements MWGift45.GiftcardSoap.BalanceInquiryAsync
            Return MyBase.Channel.BalanceInquiryAsync(Credentials, PaymentData, Request)
        End Function

        Public Function Refund(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.GiftRefundRequest) As MWGift45.GiftResponse45 Implements MWGift45.GiftcardSoap.Refund
            Return MyBase.Channel.Refund(Credentials, PaymentData, Request)
        End Function

        Public Function RefundAsync(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.GiftRefundRequest) As System.Threading.Tasks.Task(Of MWGift45.GiftResponse45) Implements MWGift45.GiftcardSoap.RefundAsync
            Return MyBase.Channel.RefundAsync(Credentials, PaymentData, Request)
        End Function

        Public Function Sale(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.GiftSaleRequest) As MWGift45.GiftResponse45 Implements MWGift45.GiftcardSoap.Sale
            Return MyBase.Channel.Sale(Credentials, PaymentData, Request)
        End Function

        Public Function SaleAsync(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.GiftSaleRequest) As System.Threading.Tasks.Task(Of MWGift45.GiftResponse45) Implements MWGift45.GiftcardSoap.SaleAsync
            Return MyBase.Channel.SaleAsync(Credentials, PaymentData, Request)
        End Function

        Public Function Void(ByVal Credentials As MWGift45.MerchantCredentials, ByVal Request As MWGift45.GiftVoidRequest) As MWGift45.GiftResponse45 Implements MWGift45.GiftcardSoap.Void
            Return MyBase.Channel.Void(Credentials, Request)
        End Function

        Public Function VoidAsync(ByVal Credentials As MWGift45.MerchantCredentials, ByVal Request As MWGift45.GiftVoidRequest) As System.Threading.Tasks.Task(Of MWGift45.GiftResponse45) Implements MWGift45.GiftcardSoap.VoidAsync
            Return MyBase.Channel.VoidAsync(Credentials, Request)
        End Function

        Public Function AddPoints(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.AddPointsRequest) As MWGift45.GiftResponse45 Implements MWGift45.GiftcardSoap.AddPoints
            Return MyBase.Channel.AddPoints(Credentials, PaymentData, Request)
        End Function

        Public Function AddPointsAsync(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.AddPointsRequest) As System.Threading.Tasks.Task(Of MWGift45.GiftResponse45) Implements MWGift45.GiftcardSoap.AddPointsAsync
            Return MyBase.Channel.AddPointsAsync(Credentials, PaymentData, Request)
        End Function

        Public Function RemovePoints(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.RemovePointsRequest) As MWGift45.GiftResponse45 Implements MWGift45.GiftcardSoap.RemovePoints
            Return MyBase.Channel.RemovePoints(Credentials, PaymentData, Request)
        End Function

        Public Function RemovePointsAsync(ByVal Credentials As MWGift45.MerchantCredentials, ByVal PaymentData As MWGift45.GiftPaymentData, ByVal Request As MWGift45.RemovePointsRequest) As System.Threading.Tasks.Task(Of MWGift45.GiftResponse45) Implements MWGift45.GiftcardSoap.RemovePointsAsync
            Return MyBase.Channel.RemovePointsAsync(Credentials, PaymentData, Request)
        End Function
    End Class
End Namespace
